[package]
name = "tadas-audio-switcher-applet"
version = "0.1.0"
edition = "2024"

[dependencies]
x11rb = "0.13"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
gtk4 = "0.9"
relm4 = "0.9"
home = "0.5"
clap = { version = "4.5", features = ["derive"] }
